palette = "catppuccin_mocha"

format = """
[░▒▓](pink)\
$directory\
[](fg:pink bg:blue)\
$git_branch\
$git_status\
[](fg:blue bg:peach)\
$nodejs\
$rust\
$golang\
$php\
[](fg:peach) \
  """

[directory]
style = "fg:base bg:pink"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bg:blue"
format = '[[ $branch ](fg:base bg:blue)]($style)'

[git_status]
style = "bg:blue"
format = '[[($all_status$ahead_behind )](fg:base bg:blue)]($style)'

[nodejs]
symbol = "Node.js"
style = "bg:peach"
format = '[[ $symbol ($version) ](fg:base bg:peach)]($style)'

[rust]
symbol = "Rust"
style = "bg:peach"
format = '[[ $symbol ($version) ](fg:base bg:peach)]($style)'

[golang]
symbol = "Golang"
style = "bg:peach"
format = '[[ $symbol ($version) ](fg:base bg:peach)]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"